version: '3'
services:
  influxdb:
    container_name: 'influxdb-monitoring'
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - monitoring

  grafana:
    container_name: 'grafana-monitoring'
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

  telegraf:
    container_name: 'telegraf-monitoring'
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - monitoring
    depends_on:
      - influxdb

networks:
  monitoring:
    driver: bridge
